server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-d97eljq8qa3s73ej674g-a.virginia-postgres.render.com:5432/platzi_play_db_n4ha 
spring.datasource.username=ronald
spring.datasource.password=jkneDGHyfB1OUI5TJpp6yJ702WKBk9eY
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=ALWAYS
langchain4j.open-ai.chat-model.api-key=demo
